---
engines:
  fixme:
    enabled: true
  hlint:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
ratings:
  paths:
    - "**.hs"
    - "**.md"
exclude_paths:
  - ".stack-work"
